package com.github.stickerifier.stickerify.junit;

import static java.lang.annotation.ElementType.TYPE;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

import org.junit.jupiter.api.extension.ExtendWith;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

/**
 * Custom annotation used to clear temp files generated by unit tests during their execution.
 *
 * @see TempFolderExtension
 */
@Retention(RUNTIME)
@Target(TYPE)
@ExtendWith(TempFolderExtension.class)
public @interface ClearTempFiles {}
