package com.github.stickerifier.stickerify.junit;

import org.junit.jupiter.api.extension.AfterAllCallback;
import org.junit.jupiter.api.extension.ExtensionContext;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Custom JUnit extension used to clear temp files
 * generated by unit tests during their execution.
 */
public class TempFilesCleanupExtension implements AfterAllCallback {

	@Override
	public void afterAll(ExtensionContext context) throws IOException {
		deleteTempFiles();
	}

	private void deleteTempFiles() throws IOException {
		var tempFolder = System.getProperty("java.io.tmpdir");
		if (tempFolder == null) return;

		try (var files = Files.list(Path.of(tempFolder))) {
			for (var file : files.toList()) {
				if (isStickerifyFile(file)) {
					Files.delete(file);
				}
			}
		}
	}

	private boolean isStickerifyFile(Path path) {
		var file = path.getFileName();
		if (file == null) return false;
		var fileName = file.toString();

		return Files.isRegularFile(path) && (fileName.startsWith("Stickerify-") || fileName.startsWith("OriginalFile-"));
	}
}
