ARG DOCKER_TAG=latest
FROM rob93c/stickerify:$DOCKER_TAG
ARG STICKERIFY_TOKEN
ARG LOG_LEVEL
ARG CONCURRENT_THREADS
ENV STICKERIFY_TOKEN=$STICKERIFY_TOKEN \
    LOG_LEVEL=$LOG_LEVEL \
    CONCURRENT_THREADS=$CONCURRENT_THREADS
