ARG DOCKER_TAG=latest
FROM rob93c/stickerify:$DOCKER_TAG
ARG STICKERIFY_TOKEN
ARG LOG_LEVEL
ARG CONCURRENT_PROCESSES
ARG VIDEO_BITRATE_LIMIT
ENV STICKERIFY_TOKEN=$STICKERIFY_TOKEN \
    LOG_LEVEL=$LOG_LEVEL \
    CONCURRENT_PROCESSES=$CONCURRENT_PROCESSES \
    VIDEO_BITRATE_LIMIT=$VIDEO_BITRATE_LIMIT
