ARG DOCKER_TAG=latest
ARG OTEL_SDK_DISABLED=false
FROM rob93c/stickerify:$DOCKER_TAG
ARG STICKERIFY_TOKEN
ARG LOG_LEVEL
ARG CONCURRENT_PROCESSES
ENV STICKERIFY_TOKEN=$STICKERIFY_TOKEN \
    LOG_LEVEL=$LOG_LEVEL \
    CONCURRENT_PROCESSES=$CONCURRENT_PROCESSES \
    OTEL_SDK_DISABLED=$OTEL_SDK_DISABLED
