name: Unit tests CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions: read-all

jobs:
  tests:
    name: Execute unit tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      security-events: write
    steps:
      - name: Checkout code changes
        uses: actions/checkout@v7

      - name: Setup FFmpeg and FFprobe
        env:
          # bump: FFmpeg /FF_VERSION: ([\d.]+)/ docker:mwader/static-ffmpeg|/\d+\./|*
          FF_VERSION: 9.0
        run: |
          INSTALL_DIR="$RUNNER_TEMP/ffmpeg"
          mkdir -p "$INSTALL_DIR"
          CID=$(docker create "mwader/static-ffmpeg:$FF_VERSION")
          docker export "$CID" | tar -xf - -C "$INSTALL_DIR" --wildcards 'ff*'
          docker rm -v "$CID" > /dev/null

          echo "$INSTALL_DIR" >> "$GITHUB_PATH"

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 26

      - name: Setup project and upload dependency graph
        uses: gradle/actions/setup-gradle@v6
        with:
          dependency-graph: generate-and-submit
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/help/legal-terms-of-use'
          build-scan-terms-of-use-agree: 'yes'

      - name: Execute tests
        shell: bash
        run: ./gradlew test

      - name: Checkout code changes
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0

      - name: Execute analysis
        uses: JetBrains/qodana-action@v2026.2.0
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          use-caches: false
          post-pr-comment: false
          pr-mode: false
          # bump: Qodana /qodana-jvm-community:([\d.]+)/ docker:jetbrains/qodana-jvm-community|/^[\d]{4}\.\d+$/|sort
          args: --image jetbrains/qodana-jvm-community:2026.2

      - name: Upload results to GitHub
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
