name: Unit tests CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  security-events: write

jobs:
  tests:
    name: Execute unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code changes
        uses: actions/checkout@v4

      - name: Setup FFmpeg
        uses: Stickerifier/setup-ffmpeg@improve-ffmpeg-downloads
        with:
          ffmpeg-version: '7.0.2'
