name: Unit tests CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  security-events: write

jobs:
  tests:
    name: Execute unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ] # pin macos to latest x64 image
    steps:
      - name: Checkout code changes
        uses: actions/checkout@v4

      - name: Setup FFmpeg
        uses: Stickerifier/setup-ffmpeg@improve-ffmpeg-downloads
        with:
          # bump: ffmpeg-ci /ffmpeg-version: '([\d.]+)'/ docker:mwader/static-ffmpeg|~7.0
          ffmpeg-version: '7.0.2'
